### ISSUE TITLE
Clicking copy in CodeSnippet causes crazy scroll expansion

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mr-ui#49]
I noticed this behavior while checking out https://www.mapbox.com/android-docs/maps/overview/annotations/#polyline-and-polygons

![oct-28-2018 21-25-49](https://user-images.githubusercontent.com/628431/47629435-3de59200-daf8-11e8-877b-f151ffc62c4c.gif)

cc @colleenmcginnis @mapbox/frontend-platform

**Comment by katydecorah** [comment]
With a copy button in a scrolled section, when you click the clipboard button the clipboard library adds a  `textarea` element to the dom, but tries to hide it through big top/left values:

![image](https://user-images.githubusercontent.com/2180540/76097210-4f189b80-5f95-11ea-82d0-ba8daff01211.png)

I think this top value is what causes the scrolled section to suddenly have a really big scroll, because when I delete the textarea from the dom, the scroll goes back to normal. I'm going to try to create a reduced test case and and create an issue in https://github.com/zenorocha/clipboard.js

**Comment by katydecorah** [comment]
I think we need to hit `this.clipboard.destroy()` after copy.

**Comment by katydecorah** [comment]
#105 fixed the original post, but introduced another issue: once the clipboard is destroyed it can't be copied again. The fix now is destroying the clipboard and then rebuilding it.
